### ISSUE TITLE
[BUG] ESRI Dynamic HFE Filter

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The HFE layer on ui component and esri dynamic demo pageis failing to refresh when we apply filter. To refresh the layer, we need to zoom in or zoom out after a new query is applied.

### Expected Behavior

As it was before, as soon as we apply a filter, the layer should refresh. It works fine with the same HFE layer but ESRI Feature

### Steps To Reproduce

1. Go to: https://canadian-geospatial-platform.github.io/geoview/public/ui-components.html for layer path error
2. Go to : https://canadian-geospatial-platform.github.io/geoview/public/esri-dynamic.html map 2 for bad refresh

### Anything else?

On ui-component page there is also an error with layer path: "historical-flood/0)"
esri-dynamic.ts:737 Uncaught TypeError: Cannot read properties of undefined (reading 'olLayer')
    at n.value (esri-dynamic.ts:737:33)
    at Object.customOnChange (ui-components.html:60:75)
    at onChangeCommitted (slider.tsx:73:61)
    at useSlider.js:438:7
    at useEventCallback.js:18:11
    at useSlider.js:398:7
    at HTMLDocument.<anonymous> (useEventCallback.js:18:11)

**Comment by jolevesq** [comment]
Solved by latest OL version
