### ISSUE TITLE
[BUG] Wrong service url crash viewer

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we try to load a service with a wrong url it crash the viewer (https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer')

### Expected Behavior

Should only set error for the bad layer and load the rest

### Steps To Reproduce

1. https://canadian-geospatial-platform.github.io/geoview/public/use-cases.html
2. Use Case 2 is not loading
```
TypeError: c.olLayer.getSource is not a function
    at c.value (esri-dynamic.ts:806:8)
    at c.value (esri-dynamic.ts:291:10)
    at abstract-geoview-layers.ts:694:43
    at Array.forEach (<anonymous>)
    at c.<anonymous> (abstract-geoview-layers.ts:687:30)
    at f (regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (regeneratorRuntime.js:133:17)
    at Generator.next (regeneratorRuntime.js:74:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
layer.ts:293 ESRI layerId must be a number (mapId:  UC2, layerPath: esriDynamicLYR2/esriDynamicLYR2)
layer.ts:293 Unable to create group layer esriDynamicLYR2/esriDynamicLYR2/0 on map UC2
```

**Comment by jolevesq** [comment]
The viewer is not crashing anymore
