### ISSUE TITLE
[BUG] GroupLayer trhow Error on Status Update

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#1999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we have a group ayer on the map i.e. esri-dynamic with 2 ids, some events throw an error
```
abstract-base-layer-entry-config.ts:28 Uncaught (in promise) TypeError: Private element is not present on this object
```

The config-base-class #emitLayerStatusChanged is not accessible from GroupLayerEntryConfig even if it extend the base class.

The work around would be to expose the event but we should not do this. We need to find the problem and fix it at the root

### Expected Behavior

We should have private event that's not raise errors

### Steps To Reproduce

1. https://canadian-geospatial-platform.github.io/geoview/public/esri-dynamic.html
2. Open console and see the error
```
cgpv-main.js:87 Uncaught (in promise) TypeError: Private element is not present on this object
    at p (cgpv-main.js:87:650373)
    at t.set (config-base-class.ts:162:7)
    at t.ae (legends-layer-set.ts:105:26)
    at t.ae (legends-layer-set.ts:110:15)
    at t.value (legends-layer-set.ts:81:13)
    at t.value (layer-set.ts:57:10)
    at layer.ts:493:18
    at Array.forEach (<anonymous>)
    at e.Oe (layer.ts:490:114)
    at layer.ts:464:11
```

**Comment by jolevesq** [comment]
RElated to #1922

**Comment by jolevesq** [comment]
Solved as part of another PR
