### ISSUE TITLE
[BUG] Class visibility not working

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#2485]
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.
no

**Current Behavior**
A concise description of what you're experiencing.
When we add this uuid 0a309f2c-4f11-4ddb-bce1-e7ba6f8c20cf, the source featureInfo is undefined and it breaks the class visbility.

```
main.62dbbe45729b8ccf.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'outfields')
    at t.H (esri-dynamic.ts:683:60)
    at t.Y (esri-dynamic.ts:719:43)
    at t.value (esri-dynamic.ts:790:39)
    at t.value (esri-dynamic.ts:944:54)
    at Function.value (map-event-processor.ts:1217:98)
    at e.value (layer.ts:1417:23)
    at Function.value (legend-event-processor.ts:520:51)
    at toggleItemVisibility (layer-state.ts:185:30)
    at onClick (layer-details.tsx:144:50)
    at Object.je (react-dom.production.min.js:54:317)
```

**NOTE: See comments below!**

**Expected Behavior**
A concise description of what you expected to happen.
fetureInfo should never be undefine

**Steps To Reproduce**
1. Go to any page
2. Click on layer, add layers
3. Add this uuid: 0a309f2c-4f11-4ddb-bce1-e7ba6f8c20cf
4. See error in console when changing class visibility

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

**Comment by jolevesq** [comment]
After some test, this is not resolve. The source is well define but when the onLoaded even is emited, the source is overwritten with default somewhere...
```
// GV Layers Refactoring - Obsolete (in layers)
  override onLoaded(layerConfig: AbstractBaseLayerEntryConfig): void {
    // Call parent
    super.onLoaded(layerConfig); AFTER THIS LINE

    // Apply view filter immediately
    this.applyViewFilter(layerConfig.layerPath, (layerConfig as 
         EsriDynamicLayerEntryConfig).layerFilter || '');
  }
```

Here is the problem
```
// Emit event
    this.#emitIndividualLayerLoaded({ layerPath: layerConfig.layerPath });
```

Use this link: https://en-fr-test.r2.osdp.aws.nrcan-rncan.cloud/dp/en/explore

cgpv.api.maps['mapWM'].layer.addGeoviewLayerByGeoCoreUUID('0a309f2c-4f11-4ddb-bce1-e7ba6f8c20cf')

**Comment by jolevesq** [comment]
After more test, it was thecreateConfigFromMapSate that was called many time in this function the feature info was reset. It is now fix by cloning the config so original one is not touch
