### ISSUE TITLE
Bug with layer panel

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView#396]
Cannot read properties of undefined (reading 'renderer')
    at geoview-layers-panel.js:formatted:1257:73
    at Array.map (<anonymous>)
    at geoview-layers-panel.js:formatted:1198:41
    at Array.map (<anonymous>)
    at E (geoview-layers-panel.js:formatted:1062:44)
    at sa (gcpv-main.js:200:752408)
    at Ua (gcpv-main.js:200:761926)
    at qs (gcpv-main.js:200:805463)
    at Ll (gcpv-main.js:200:791762)
    at El (gcpv-main.js:200:791690)

May have been introduce by type

**Comment by yass0016** [comment]
Fixed in a previous PR
