### ISSUE TITLE
Unable to getLegend() for some layers

### ISSUE THREAD

**Issue by dayc-mapdev** [Canadian-Geospatial-Platform/GeoView#631]
Trying to get the legend for some layers fails. See
https://canadian-geospatial-platform.github.io/geoview/public/legend.html
3. Group Layers - Expand all the group layers. When it tries to get the legend for 'Basin borders' layer it fails.

This layer
https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/2

Error message
```
map-schema-types.ts:148 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at r (map-schema-types.ts:148:25)
    at e.value (geoview-renderer.ts:685:9)
    at geoview-renderer.ts:361:62
    at Array.forEach (<anonymous>)
    at geoview-renderer.ts:360:55
    at new Promise (<anonymous>)
    at e.value (geoview-renderer.ts:323:32)
    at abstract-geoview-layers.ts:760:25
    at new Promise (<anonymous>)
    at n.value (abstract-geoview-layers.ts:750:28)
```

**Comment by dayc-mapdev** [comment]
Confirmed fixed
