### ISSUE TITLE
Error on WMS layer

### ISSUE THREAD

**Issue by dayc-mapdev** [Canadian-Geospatial-Platform/geoview#644]
legend.html / Map 1 WMS layer is not shown. This is the layer config:

```
              {
                'geoviewLayerId': 'wmsLYR7',
                'geoviewLayerName': {
                  'en': 'Geomet (WMS)',
                  'fr': 'Geomet'
                },
                'metadataAccessPath': {
                  'en': 'https://geo.weather.gc.ca/geomet',
                  'fr': 'https://geo.weather.gc.ca/geomet'
                },
                'geoviewLayerType': 'ogcWms',
                'listOfLayerEntryConfig': [{ 'layerId': 'RAQDPS-FW.CE_PM2.5-DIFF-YAvg' }]
              },
```

Error message:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at wms.ts:183:56
    at Array.forEach (<anonymous>)
    at WMS.processMetadataInheritance (wms.ts:181:44)
    at wms.ts:189:94
    at Array.forEach (<anonymous>)
    at WMS.processMetadataInheritance (wms.ts:189:67)
    at wms.ts:189:94
    at Array.forEach (<anonymous>)
    at WMS.processMetadataInheritance (wms.ts:189:67)
    at wms.ts:119:18
```

**Comment by dayc-mapdev** [comment]
Fixed with #660
