### ISSUE TITLE
EsriFeature Layer not loading

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#744]
https://gisp.dfo-mpo.gc.ca/arcgis/rest/services/FGP/MSDI_Dynamic_Current_Layer/MapServer/0
```
geoview-renderer.ts:1138 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at geoview-renderer.ts:1138:50
```

https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/U2/FeatureServer/
```
esri-feature.ts:255 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at esri-feature.ts:255:45
response.data.geometryField.name as string, is undefined
```

**Comment by ychoquet** [comment]
The bug related to the second url (https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/U2/FeatureServer/0) is simple to resolve and will be corrected with the PR related to issues 757

**Comment by ychoquet** [comment]
This issue seems to be resolved. Error messages similar to those depicted were resolve in an other PR that had the same problems. I'm unable to test it for the moment because the server is down.

**Comment by jolevesq** [comment]
There is 2 errors when adding from add layer panel

```
logger.ts:421 08:28:03.258 Error detected while reading Layer metadata. TypeError: Cannot read properties of undefined (reading 'latestWkid')
    at t.value (esri-feature-layer-entry-config.ts:73:47)
    at t.<anonymous> (abstract-base-esri-layer-entry-config.ts:48:12)

logger.ts:421 08:28:11.684 Error: Invalid Date (convertToMilliseconds)
    at e.value (date-mgt.ts:299:63)
    at abstract-geoview-vector.ts:246:43
    at Array.forEach (<anonymous>)
    at abstract-geoview-vector.ts:240:18
    at Array.forEach (<anonymous>)
    at t.$ (abstract-geoview-vector.ts:239:14)
    at abstract-geoview-vector.ts:131:34
```

**Comment by DamonU2** [comment]
First link no longer exists, new location is https://egisp.dfo-mpo.gc.ca/arcgis/rest/services/open_data_donnees_ouvertes/msdi_dynamic_current_layer_couche_dynamique_de_courant_idsm/MapServer/0
Now has fetch issues due to fetching over 7 million features a thousand at a time
