### ISSUE TITLE
WMS layer failed to load

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/geoview#765]
All wms are failing in demo page

Layer wmsLYR1-msi failed to load on map LYR1
wms.ts:417 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at wms.ts:417:59
    at new Promise (<anonymous>)
    at n.value (wms.ts:384:32)
    at abstract-geoview-layers.ts:300:45
    at Array.forEach (<anonymous>)
    at abstract-geoview-layers.ts:296:30
    at new Promise (<anonymous>)
    at n.value (abstract-geoview-layers.ts:294:47)
    at abstract-geoview-layers.ts:260:16

**Comment by DamonU2** [comment]
Unable to reproduce, seems to have been fixed.
